### PR TITLE
Ci health dependency issue

### PR DESCRIPTION
**Pull request by dhiller**
* Move urls to github.com/kubevirt
* update protobuf dependency

/cc @brianmcarey

### CODE REVIEW

**Comment by enp0s3** [comment]
@dhiller kudos for using `shallow_since` :) it should save BW I guess.

**Comment by dhiller** [comment]
> @dhiller kudos for using `shallow_since` :) it should save BW I guess.

The kudos are owed to the bazel developer who added that hint when running the build :slightly_smiling_face:

**Comment by dhiller** [comment]
Note to self: we must not use the usual fork merge model here, but instead push to the origin remote, otherwise the GitHub actions will not work.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
